import '../model/letter_card_model.dart';

List<LetterCardModel> letters = [
  LetterCardModel(letter: 'A'),
  LetterCardModel(letter: 'B'),
  LetterCardModel(letter: 'C'),
  LetterCardModel(letter: 'D'),
  LetterCardModel(letter: 'E'),
  LetterCardModel(letter: 'F'),
  LetterCardModel(letter: 'G'),
  LetterCardModel(letter: 'H'),
  LetterCardModel(letter: 'I'),
  LetterCardModel(letter: 'J'),
  LetterCardModel(letter: 'K'),
  LetterCardModel(letter: 'L'),
  LetterCardModel(letter: 'M'),
  LetterCardModel(letter: 'N'),
  LetterCardModel(letter: 'O'),
  LetterCardModel(letter: 'P'),
  LetterCardModel(letter: 'Q'),
  LetterCardModel(letter: 'R'),
  LetterCardModel(letter: 'S'),
  LetterCardModel(letter: 'T'),
  LetterCardModel(letter: 'U'),
  LetterCardModel(letter: 'V'),
  LetterCardModel(letter: 'W'),
  LetterCardModel(letter: 'X'),
  LetterCardModel(letter: 'Y'),
  LetterCardModel(letter: 'Z'),
];